- name: install the packages needed to build libbdvmi
  apt:
    name:
      - libboost-all-dev
      - libxen-dev
      - pkg-config
      - uuid-dev
    state: present

- name: fetch the libbdvmi sources
  git:
    repo: https://github.com/bitdefender/libbdvmi.git
    dest: /usr/src/libbdvmi
    version: master

- name: build and install libbdvmi
  shell: |
    ./bootstrap
    mkdir build
    cd build
    ../configure --prefix=/usr/local --enable-kvmi --enable-optimize
    make
    make install
    cd ..
    rm -rf build
  args:
    chdir: /usr/src/libbdvmi