- name: install qemu-kvm build dependencies
  apt:
    name: qemu-kvm
    state: build-dep

# TODO: do as user
- name: fetch qemu with the KVMI patches
  git:
    repo: https://github.com/KVM-VMI/qemu.git
    dest: /usr/src/qemu-kvmi
    version: kvmi-v7

- name: build and install the KVMI enabled qemu
  shell: |
    mkdir build
    cd build
    ../configure --prefix=/usr/local --python=`which python3` --target-list=x86_64-softmmu --disable-werror
    make -j`nproc`
    make install
    cd ..
    rm -rf build
  args:
    chdir: /usr/src/qemu-kvmi

- name: reconfigure qemu for libvirt
  replace:
    path: /etc/libvirt/qemu.conf
    regexp: "([\\W\\w]*)(#cgroup_device_acl[^\\]]+#\\])([\\W\\w]*)"
    replace: |
      \1
      cgroup_device_acl = [
          "/dev/null", "/dev/full", "/dev/zero",
          "/dev/random", "/dev/urandom",
          "/dev/ptmx", "/dev/kvm", "/dev/kqemu",
          "/dev/rtc", "/dev/hpet", "/dev/vfio/vfio",
          "/dev/vhost-vsock"
      ]
      \3