- name: install qemu-kvm build dependencies
  apt:
    name: qemu-kvm
    state: build-dep

- name: fetch qemu with the KVMI patches
  git:
    repo: https://github.com/KVM-VMI/qemu.git
    dest: /home/demo/qemu
    version: kvmi-v7
  become: false

- name: create build dir
  file:
    path: /home/demo/qemu/build
    state: directory
  become: false

- name: configure qemu
  command: ../configure --prefix=/usr/local --python=`which python3` --target-list=x86_64-softmmu --disable-werror
  args:
    chdir: /home/demo/qemu/build
  become: false

- name: build qemu
  make:
    chdir: /home/demo/qemu/build
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"
  become: false

- name: install qemu
  make:
    chdir: /home/demo/qemu/build
    target: install

- name: delete build directory
  file:
    path: /home/demo/qemu/build
    state: absent
  become: false

- name: reconfigure qemu for libvirt
  replace:
    path: /etc/libvirt/qemu.conf
    regexp: "([\\W\\w]*)(#cgroup_device_acl[^\\]]+#\\])([\\W\\w]*)"
    replace: |
      \1
      cgroup_device_acl = [
          "/dev/null", "/dev/full", "/dev/zero",
          "/dev/random", "/dev/urandom",
          "/dev/ptmx", "/dev/kvm", "/dev/kqemu",
          "/dev/rtc", "/dev/hpet", "/dev/vfio/vfio",
          "/dev/vhost-vsock"
      ]
      \3
