- name: install libkvmi deps
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - libtool

- name: fetch the libkvmi sources
  git:
    repo: https://github.com/bitdefender/libkvmi.git
    dest: /home/demo/libkvmi
    version: master
  become: false

- name: bootstrap libkvmi
  command: ./bootstrap
  args:
    chdir: /home/demo/libkvmi
  become: false

- name: create build dir
  file:
    path: /home/demo/libkvmi/build
    state: directory
  become: false

- name: configure libkvmi
  command: ../configure --prefix=/usr/local --enable-optimize
  args:
    chdir: /home/demo/libkvmi/build
  become: false

- name: build libkvmi
  make:
    chdir: /home/demo/libkvmi/build
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"
  become: false

- name: install libkvmi
  make:
    chdir: /home/demo/libkvmi/build
    target: install

- name: delete build directory
  file:
    path: /home/demo/libkvmi/build
    state: absent
  become: false

