---
  # input variables:
  #   image_type: (str): whether we should provision a host or a guest KVMi image ("guest" | "host")
- hosts: all
  become: true
  pre_tasks:

    - name: update the apt cache
      apt:
        update_cache: yes
  roles:
    - kvm

    - role: libbdvmi
      when: image_type == 'guest'

    - role: hvmi
      when: image_type == 'guest'

    - role: libvirt
      when: image_type == 'host'

    - role: qemu
      when: image_type == 'host'
