- name: install the packages needed to build hvmi
  apt:
    name:
      - cmake
      - libjsoncpp-dev
    state: present

- name: fetch the hvmi sources
  git:
    repo: https://github.com/hvmi/hvmi.git
    dest: /home/demo/hvmi
    version: master
    recursive: yes
  become: false

- name: configure hvmi
  command: cmake -Bbuild -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release
  args:
    chdir: /home/demo/hvmi
  become: false

- name: build hvmi
  command: cmake --build build
  args:
    chdir: /home/demo/hvmi
  become: false

- name: install hvmi
  command: cmake --build build --target install
  args:
    chdir: /home/demo/hvmi

- name: configure hvmi daemon
  command: cmake -Bbuild -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release
  args:
    chdir: /home/demo/hvmi/daemon
  become: false

- name: build hvmi daemon
  command: cmake --build build
  args:
    chdir: /home/demo/hvmi/daemon
  become: false

- name: install hvmi daemon
  command: cmake --build build --target install
  args:
    chdir: /home/demo/hvmi/daemon

